### ISSUE TITLE
Add taxon ID to gene_info.json

### ISSUE THREAD

**Issue by dustine32** [pantherdb/panther-stats-demo#1]
Add Taxon ID to the `gene_info.json`. Example:
```
    {
        "gene": "MGI:MGI:99423",
        "gene_symbol": "Etv4",
        "gene_name": "ETS translocation variant 4",
        "taxon_id": "10090"
    },
```
I can likely source this from the hacked [createGAF_human_exp_references.pl](https://github.com/pantherdb/fullgo_paint_update/blob/master/scripts/createGAF_human_exp_references.pl).

**Comment by tmushayahama** [comment]
@dustine32 will you be provide a map for the into taxon metadata or we will use api

**Comment by dustine32** [comment]
@tmushayahama Oh yeah, that'll be covered in #10.
