### ISSUE TITLE
Fill empty "slim_terms" field with "Other" phrase in annotation JSON

### ISSUE THREAD

**Issue by dustine32** [pantherdb/panther-stats-demo#3]
In IBA annotations, occasionally the term doesn't have any slim terms. This is because the annotated term has no ancestors in the GO generic slim. Fill with "Other..." value matching the aspect of annotated term:
* Other molecular function
* Other biological process
* Other cellular component
```
    {
        "gene": "UniProtKB:P15036",
        "gene_symbol": "ETS2",
        "gene_name": "Protein C-ets-2",
        "term": "GO:0000981",
        "slim_terms": [
            "Other molecular function"
        ],
    }
```
@tmushayahama Does this solution make sense? Is it easy to implement with how we load the indexer? Or should we create some dummy term IDs for these in the ontology JSON like this?
```
    {
        "ID": "OTHER:0001",
        "LABEL": "Other molecular function",
        ...
    }
```
And then we would specify `slim_terms` in the annotation JSON by the dummy ID? So, the annotation example above would become:
```
    {
        "gene": "UniProtKB:P15036",
        "gene_symbol": "ETS2",
        "gene_name": "Protein C-ets-2",
        "term": "GO:0000981",
        "slim_terms": [
            "OTHER:0001"
        ],
    }
```

**Comment by tmushayahama** [comment]
@dustine32 let create some dummy term ids. with also aspect. Thanks

**Comment by dustine32** [comment]
@tmushayahama Will do, thanks! So our example term will look like:
```
    {
        "ID": "OTHER:0001",
        "LABEL": "Other molecular function",
        "hasOBONamespace": "molecular_function",
        "is_goslim": true
    }
```
