### ISSUE TITLE
Change "qualifiers" field name to "relation"

### ISSUE THREAD

**Issue by dustine32** [pantherdb/panther-stats-demo#7]
For the human functionome site, "qualifiers" is kind of an awkward term since the displayed values are relations in RO. The field is also not an array so it should be singular.

@dustine32 will change the field name in the annotation JSON file. @tmushayahama will change the field in the UI unless this is just automatically pulled from the input JSON field name.

**Comment by tmushayahama** [comment]
Also while you on it, shouldn't there be one qualifier?

**Comment by thomaspd** [comment]
I can't remember if the prototype was showing a qualifier for all the annotations, or just some of them. What are the unique values of this field?

**Comment by dustine32** [comment]
Here's the list of distinct qualifiers/relations in the input GAF 2.2 file:
enables
part_of
contributes_to
colocalizes_with
is_active_in
involved_in

Since this is from [GAF 2.2](http://geneontology.org/docs/go-annotation-file-gaf-format-2.2/#qualifier-column-4) there will always be some relation. The only case where there's more than one relation is in a `NOT` annotation (e.g., `NOT|enables`), but we're filtering out all `NOT`s here, so there will only ever be one relation in this field.

**Comment by dustine32** [comment]
From 2022-11-21 call - Only show contributes_to, colocalizes_with qualifiers. No standard relations. Change field name to "qualifier". Cardinality will be 0 or 1.

**Comment by dustine32** [comment]
Closing as fixed
